<!--
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_LoyaltyRule
 * @author    Webkul
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
-->
<?php
    $blockGrid = $block->getBlockGrid();
    $gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml(); ?>
<input data-form-part="loyalty_rule_form" 
    type="hidden" 
    name="loyalty_rule[selected_rule_category]" 
    id="selected_rule_category" 
    value=""/>

<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_LoyaltyRule/js/assign-categories": {
                "selectedCategory" : <?= /* @noEscape */ $block->getSelectedCategoryData() ?>,
                "gridJsObjectName" : <?= /* @noEscape */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script type="text/javascript">
    require("mage/apply/main").apply();
</script>
